Improved init script

diff --git a/ddhcpd/files/etc/init.d/ddhcpd b/ddhcpd/files/etc/init.d/ddhcpd
--- a/ddhcpd/files/etc/init.d/ddhcpd
+++ b/ddhcpd/files/etc/init.d/ddhcpd
@@ -3,21 +3,49 @@
 START=90
 USE_PROCD=1
 
+NAME=ddhcpd
 DAEMON=/usr/sbin/ddhcpd
 MAXDELAY=10
 
+validate_section_ddhcpd() {
+  uci_validate_section "$NAME" ddhcpd settings \
+  'dhcp_interface:string:br-client' \
+  'server_interface:string:br-client' \
+  'block_size_pow:uinteger:2' \
+  'spare_blocks:uinteger:1' \
+  'timeout:uinteger:30' \
+  'block_network:cidr4' \
+  'dhcp_lease_time:uinteger:300'
+}
+
 start_service() {
-        [ -x /lib/gluon/ddhcpd/arguments ] || exit 1
+  [ -x /lib/gluon/ddhcpd/arguments ] || exit 1
 
-        local ifdump="$(ubus call network.interface dump)"
-        
-        local clientdevs=$(for dev in $(echo "$ifdump" | jsonfilter -e "@.interface[@.interface='client' && @.up=true].device"); do echo " -c $dev ";done;)
-        local servicedevs=$(for dev in $(echo "$ifdump" | jsonfilter -e "@.interface[@.interface='client' && @.up=true].device"); do echo " -i $dev ";done;)
+  procd_open_instance
+  procd_set_param command $DAEMON -D 
 
-        procd_open_instance
-        procd_set_param command $DAEMON -D $(/lib/gluon/ddhcpd/arguments) -b 2 -s 1 ${clientdevs} ${servicedevs}
-        procd_set_param respawn ${respawn_threshold:-3600} ${respawn_timeout:-5} ${respawn_retry:-5}
-        procd_set_param netdev "br-client"
-        procd_set_param stderr 1
-        procd_close_instance
+  config_load "${NAME}"
+
+  validate_section_ddhcpd || {
+    echo "validation failed"
+    return 1
+  }
+
+  procd_append_param command -s "$spare_blocks"
+  procd_append_param command -b "$block_size_pow"
+  procd_append_param command -c "$dhcp_interface"
+  procd_append_param command -i "$server_interface"
+  procd_append_param command -N "$block_network"
+  procd_append_param command -o "51:4:0.0.1.44"
+  procd_append_param command $(/lib/gluon/ddhcpd/arguments)
+  procd_set_param respawn
+  procd_set_param netdev "$dhcp_interface"
+  [ "$dhcp_interface" == "$server_interface" ] || procd_append_param netdev "$server_interface"
+  procd_set_param stderr 1
+  procd_close_instance
+}
+
+service_triggers() {
+  procd_add_config_trigger "config.change" "ddhcpd" /etc/init.d/ddhcpd restart
+  procd_add_interface_trigger "interface.*" "br-client" /etc/init.d/ddhcpd restart
 }
